// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.security;

import com.app2.app2t.domain.security.AppRoleMenu;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AppRoleMenu_Roo_Configurable {
    
    declare @type: AppRoleMenu: @Configurable;
    
}
