// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.security;

import com.app2.app2t.domain.security.AppMenu;
import com.app2.app2t.domain.security.AppMenuDataOnDemand;
import com.app2.app2t.domain.security.AppMenuIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppMenuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppMenuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppMenuIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppMenuIntegrationTest: @Transactional;
    
    @Autowired
    AppMenuDataOnDemand AppMenuIntegrationTest.dod;
    
    @Test
    public void AppMenuIntegrationTest.testCountAppMenus() {
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", dod.getRandomAppMenu());
        long count = AppMenu.countAppMenus();
        Assert.assertTrue("Counter for 'AppMenu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppMenuIntegrationTest.testFindAppMenu() {
        AppMenu obj = dod.getRandomAppMenu();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to provide an identifier", id);
        obj = AppMenu.findAppMenu(id);
        Assert.assertNotNull("Find method for 'AppMenu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppMenu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppMenuIntegrationTest.testFindAllAppMenus() {
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", dod.getRandomAppMenu());
        long count = AppMenu.countAppMenus();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppMenu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppMenu> result = AppMenu.findAllAppMenus();
        Assert.assertNotNull("Find all method for 'AppMenu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppMenu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppMenuIntegrationTest.testFindAppMenuEntries() {
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", dod.getRandomAppMenu());
        long count = AppMenu.countAppMenus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppMenu> result = AppMenu.findAppMenuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppMenu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppMenu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppMenuIntegrationTest.testFlush() {
        AppMenu obj = dod.getRandomAppMenu();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to provide an identifier", id);
        obj = AppMenu.findAppMenu(id);
        Assert.assertNotNull("Find method for 'AppMenu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppMenu(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppMenu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppMenuIntegrationTest.testMergeUpdate() {
        AppMenu obj = dod.getRandomAppMenu();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to provide an identifier", id);
        obj = AppMenu.findAppMenu(id);
        boolean modified =  dod.modifyAppMenu(obj);
        Integer currentVersion = obj.getVersion();
        AppMenu merged = (AppMenu)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppMenu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppMenuIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", dod.getRandomAppMenu());
        AppMenu obj = dod.getNewTransientAppMenu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppMenu' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AppMenu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppMenuIntegrationTest.testRemove() {
        AppMenu obj = dod.getRandomAppMenu();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppMenu' failed to provide an identifier", id);
        obj = AppMenu.findAppMenu(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppMenu' with identifier '" + id + "'", AppMenu.findAppMenu(id));
    }
    
}
