// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app2.app2t.domain.security;

import com.app2.app2t.domain.security.AppRoleMenu;
import com.app2.app2t.domain.security.AppRoleMenuDataOnDemand;
import com.app2.app2t.domain.security.AppRoleMenuIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppRoleMenuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppRoleMenuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppRoleMenuIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppRoleMenuIntegrationTest: @Transactional;
    
    @Autowired
    AppRoleMenuDataOnDemand AppRoleMenuIntegrationTest.dod;
    
    @Test
    public void AppRoleMenuIntegrationTest.testCountAppRoleMenus() {
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", dod.getRandomAppRoleMenu());
        long count = AppRoleMenu.countAppRoleMenus();
        Assert.assertTrue("Counter for 'AppRoleMenu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testFindAppRoleMenu() {
        AppRoleMenu obj = dod.getRandomAppRoleMenu();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to provide an identifier", id);
        obj = AppRoleMenu.findAppRoleMenu(id);
        Assert.assertNotNull("Find method for 'AppRoleMenu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppRoleMenu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testFindAllAppRoleMenus() {
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", dod.getRandomAppRoleMenu());
        long count = AppRoleMenu.countAppRoleMenus();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppRoleMenu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppRoleMenu> result = AppRoleMenu.findAllAppRoleMenus();
        Assert.assertNotNull("Find all method for 'AppRoleMenu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppRoleMenu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testFindAppRoleMenuEntries() {
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", dod.getRandomAppRoleMenu());
        long count = AppRoleMenu.countAppRoleMenus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppRoleMenu> result = AppRoleMenu.findAppRoleMenuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppRoleMenu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppRoleMenu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testFlush() {
        AppRoleMenu obj = dod.getRandomAppRoleMenu();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to provide an identifier", id);
        obj = AppRoleMenu.findAppRoleMenu(id);
        Assert.assertNotNull("Find method for 'AppRoleMenu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppRoleMenu(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppRoleMenu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testMergeUpdate() {
        AppRoleMenu obj = dod.getRandomAppRoleMenu();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to provide an identifier", id);
        obj = AppRoleMenu.findAppRoleMenu(id);
        boolean modified =  dod.modifyAppRoleMenu(obj);
        Integer currentVersion = obj.getVersion();
        AppRoleMenu merged = (AppRoleMenu)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppRoleMenu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", dod.getRandomAppRoleMenu());
        AppRoleMenu obj = dod.getNewTransientAppRoleMenu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppRoleMenu' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'AppRoleMenu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppRoleMenuIntegrationTest.testRemove() {
        AppRoleMenu obj = dod.getRandomAppRoleMenu();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppRoleMenu' failed to provide an identifier", id);
        obj = AppRoleMenu.findAppRoleMenu(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppRoleMenu' with identifier '" + id + "'", AppRoleMenu.findAppRoleMenu(id));
    }
    
}
